{
    "targets":[
        {
            "target_name":"addon",
            "sources":[
                "addon.cc",
                "myobject.h",
                "myobject.cc",
            ],
        }
    ]
}